### ISSUE TITLE
BarcodeScanner logo design

### ISSUE THREAD

**Issue by reallinfo** [dansiegel/BarcodeScanner#1]
Hello again! I designed a few logo for the barcode scanner. How do these look?

![barcodescanner](https://user-images.githubusercontent.com/36298335/40330634-419feec4-5d56-11e8-82cf-b79f95da52d6.jpg)

**Comment by dansiegel** [comment]
that actually looks great.

**Comment by reallinfo** [comment]
oh, okay. i sent all the files.

https://github.com/dansiegel/BarcodeScanner/pulls
