### ISSUE TITLE
Any support for external wire-connected (USB) barcode scanners?

### ISSUE THREAD

**Issue by dbnex14** [dansiegel/BarcodeScanner#3]
I see this library supports scanning using Camera.
Any support for externally, wire-connected over USB barcode scanners for all 3 platforms (Android, IOS, and UWP) in Xamarin.Forms?

**Comment by dansiegel** [comment]
Well that wouldn't make much sense as Android and iOS devices don't have a USB connection so it's not like you could program against using a single Scanner. Theoretically you could with a Bluetooth Scanner, but again it's not generally something the people do with a mobile device. The idea of this isn't to be all things to all people, but to take the idea of barcode scanning with the camera (which is what most people rely on) and abstract it in a reusable way.

**Comment by dbnex14** [comment]
@dansiegel Thanks Dan but I know mobile devices and tablets dont have USB ports and I know they are "mobile" but businesses like restaurant, or large terminals attach tablets or even phones to a housing with USB connection and connect it to a handheld barcode scanner like Xenon 1900 for example ([https://www.youtube.com/watch?v=Ih1gmyXMN3g](https://www.youtube.com/watch?v=Ih1gmyXMN3g)
That way you have your iPad or other tablet or even now an iPhone sitting in the docking station and they just use the wired attached barcode scanner to do scanning in a fast and efficient way.
Honestly, no one in industry will use camera scanner since it is very slow, only as a backup and that maybe, say a person has to walk away from the docking station.  I worked at places where they need to scan at least 1 item per second but it would sometime be 2 or 3 items.  But even if you scan only one every few seconds, a user has no time to wait on camera to show and focus, they need to do other work if they dont do actual scanning. And now I work on POS and they dont want to use camera as it is to  slow and not practical.
So, your point about mobile or tablets using camera primarily is valid but for regular phone user that wants to scan a barcode while waiting on a train station or something.  Not for businesses that do a crazy amount of scanning every hour.
